11/7/2016 17:59:50.495;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.526;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.541;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.573;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.604;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.619;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.619;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.635;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.651;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.666;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.682;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.697;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.713;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.729;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.744;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.775;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.791;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.822;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.838;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.853;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.885;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.916;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.931;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.931;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.963;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:50.978;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:51.006;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:51.021;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:51.026;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:51.042;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:51.057;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:51.089;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:51.120;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:51.135;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:51.151;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:51.169;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:51.185;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
