11/7/2016 17:59:52.414;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:52.461;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:52.476;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:52.476;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:52.492;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:52.508;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:52.523;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:52.539;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:52.539;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:52.554;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:52.570;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:52.586;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:52.601;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:52.617;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:52.617;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:52.632;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:52.648;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:52.664;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 17:59:52.679;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 18:00:13.436;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 18:00:29.613;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 18:01:16.071;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
11/7/2016 18:28:57.178;ERROR;;"Failure sending mail.";"{""ExceptionData"":{""InnerExceptionMessage"":""Unable to connect to the remote server"",""InnerExceptionStackTrace"":""   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)\r\n   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)\r\n   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)\r\n   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)\r\n   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)\r\n   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)\r\n   at System.Net.Mail.SmtpClient.GetConnection()\r\n   at System.Net.Mail.SmtpClient.Send(MailMessage message)"",""ManualMessage"":null,""ExceptionMessage"":""Failure sending mail."",""ExceptionStackTrace"":""   at System.Net.Mail.SmtpClient.Send(MailMessage message)\r\n   at AdvantShop.Mails.SendMail.SendMailThreadStringResult(String strTo, String strSubject, String strText, Boolean isBodyHtml, String smtpServer, String login, String password, Int32 port, String emailFrom, Boolean ssl, String attachement) in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Mails\\SendMail.cs:line 59"",""Parameters"":{}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
12/7/2016 0:07:27.105;ERROR;;"Failure sending mail.";"{""ExceptionData"":{""InnerExceptionMessage"":""Unable to connect to the remote server"",""InnerExceptionStackTrace"":""   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)\r\n   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)\r\n   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)\r\n   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)\r\n   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)\r\n   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)\r\n   at System.Net.Mail.SmtpClient.GetConnection()\r\n   at System.Net.Mail.SmtpClient.Send(MailMessage message)"",""ManualMessage"":null,""ExceptionMessage"":""Failure sending mail."",""ExceptionStackTrace"":""   at System.Net.Mail.SmtpClient.Send(MailMessage message)\r\n   at AdvantShop.Mails.SendMail.SendMailThreadStringResult(String strTo, String strSubject, String strText, Boolean isBodyHtml, String smtpServer, String login, String password, Int32 port, String emailFrom, Boolean ssl, String attachement) in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Mails\\SendMail.cs:line 59"",""Parameters"":{}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
12/7/2016 8:37:27.687;ERROR;Problem with CsvEnconing;"A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - The network connection was aborted by the local system.)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network connection was aborted by the local system"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - The network connection was aborted by the local system.)"",""ExceptionStackTrace"":""   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)\r\n   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()\r\n   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()\r\n   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()\r\n   at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()\r\n   at System.Data.SqlClient.SqlDataReader.get_MetaData()\r\n   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)\r\n   at System.Data.SqlClient.SqlCommand.ExecuteScalar()\r\n   at AdvantShop.Core.SQLDataAccess.ExecuteScalar[TResult](String commandText, CommandType commandType, SqlParameter[] parameters) in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 86\r\n   at AdvantShop.Configuration.SettingProvider.GetSqlSettingValueFromDB(String strName) in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Configuration\\ProviderSetting.cs:line 120\r\n   at AdvantShop.Configuration.SettingProvider.GetSqlSettingValue(String strName) in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Configuration\\ProviderSetting.cs:line 110\r\n   at AdvantShop.Configuration.SettingProvider.SettingIndexer.get_Item(String name) in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Configuration\\ProviderSetting.cs:line 29\r\n   at AdvantShop.Configuration.SettingsGeneral.get_CsvEnconing() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Configuration\\SettingsGeneral.cs:line 65\r\n   at AdvantShop.Helpers.CsvHelper.Encodings.get_CsvEnconing() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Helpers\\CsvHelper\\Encodings.cs:line 64"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""1236"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
12/7/2016 8:38:11.718;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
12/7/2016 8:38:11.718;ERROR;Problem with CsvEnconing;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 415\r\n   at AdvantShop.Core.SQLDataAccess.ExecuteScalar[TResult](String commandText, CommandType commandType, SqlParameter[] parameters) in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 85\r\n   at AdvantShop.Configuration.SettingProvider.GetSqlSettingValueFromDB(String strName) in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Configuration\\ProviderSetting.cs:line 120\r\n   at AdvantShop.Configuration.SettingProvider.GetSqlSettingValue(String strName) in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Configuration\\ProviderSetting.cs:line 110\r\n   at AdvantShop.Configuration.SettingProvider.SettingIndexer.get_Item(String name) in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Configuration\\ProviderSetting.cs:line 29\r\n   at AdvantShop.Configuration.SettingsGeneral.get_CsvEnconing() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Configuration\\SettingsGeneral.cs:line 65\r\n   at AdvantShop.Helpers.CsvHelper.Encodings.get_CsvEnconing() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Helpers\\CsvHelper\\Encodings.cs:line 64"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
12/7/2016 8:38:48.849;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
12/7/2016 8:39:25.902;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
12/7/2016 8:39:25.902;ERROR;Problem with CsvEnconing;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 415\r\n   at AdvantShop.Core.SQLDataAccess.ExecuteScalar[TResult](String commandText, CommandType commandType, SqlParameter[] parameters) in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 85\r\n   at AdvantShop.Configuration.SettingProvider.GetSqlSettingValueFromDB(String strName) in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Configuration\\ProviderSetting.cs:line 120\r\n   at AdvantShop.Configuration.SettingProvider.GetSqlSettingValue(String strName) in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Configuration\\ProviderSetting.cs:line 110\r\n   at AdvantShop.Configuration.SettingProvider.SettingIndexer.get_Item(String name) in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Configuration\\ProviderSetting.cs:line 29\r\n   at AdvantShop.Configuration.SettingsGeneral.get_CsvEnconing() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Configuration\\SettingsGeneral.cs:line 65\r\n   at AdvantShop.Helpers.CsvHelper.Encodings.get_CsvEnconing() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Helpers\\CsvHelper\\Encodings.cs:line 64"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
12/7/2016 8:40:37.526;ERROR;Data Source=w07.hoster.by; Initial Catalog=instrume_db; Persist Security Info='True'; User ID=instrume_sa; Password=NesUser1;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 408"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
12/7/2016 8:40:37.526;ERROR;Problem with CsvEnconing;"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)";"{""ExceptionData"":{""InnerExceptionMessage"":""The network path was not found"",""InnerExceptionStackTrace"":null,""ManualMessage"":null,""ExceptionMessage"":""A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"",""ExceptionStackTrace"":""   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at AdvantShop.Core.SQLDataAccess.cnOpen() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 415\r\n   at AdvantShop.Core.SQLDataAccess.ExecuteScalar[TResult](String commandText, CommandType commandType, SqlParameter[] parameters) in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Core\\SQL\\SQLDataAccess.cs:line 85\r\n   at AdvantShop.Configuration.SettingProvider.GetSqlSettingValueFromDB(String strName) in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Configuration\\ProviderSetting.cs:line 120\r\n   at AdvantShop.Configuration.SettingProvider.GetSqlSettingValue(String strName) in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Configuration\\ProviderSetting.cs:line 110\r\n   at AdvantShop.Configuration.SettingProvider.SettingIndexer.get_Item(String name) in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Configuration\\ProviderSetting.cs:line 29\r\n   at AdvantShop.Configuration.SettingsGeneral.get_CsvEnconing() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Configuration\\SettingsGeneral.cs:line 65\r\n   at AdvantShop.Helpers.CsvHelper.Encodings.get_CsvEnconing() in d:\\Personal\\WORK\\NesProject\\InstrumentOptBy\\App_Code\\AdvantShop\\Helpers\\CsvHelper\\Encodings.cs:line 64"",""Parameters"":{""HelpLink.ProdName"":""Microsoft SQL Server"",""HelpLink.EvtSrc"":""MSSQLServer"",""HelpLink.EvtID"":""53"",""HelpLink.BaseHelpUrl"":""http://go.microsoft.com/fwlink"",""HelpLink.LinkId"":""20476""}},""RequestData"":null,""BrowserData"":null,""SessionData"":null}";
